runtime: python
env: flex

runtime_config:
    python_version: 3

resources:
    cpu: 1
    memory_gb: 3
    disk_size_gb: 10
manual_scaling:
    instances:2

entrypoint: gunicorn -b localhost:8000 app:server
